Repository iScsc/iscsc.fr, pull requests merged in 2022-11, with the labels that each got.

#20 V0.2.0: production and development mode
  .env.example
  .gitignore
  README.md
  backend/.env.example
  backend/Dockerfile
  backend/app.js
  backend/package-lock.json
  backend/package.json
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ArticleForm.js
  frontend/src/components/ArticlePreview.js
  frontend/src/config.json
  frontend/src/config/config.json
  frontend/src/hooks/useLogin.js
  frontend/src/hooks/useSignup.js
  frontend/src/pages/blog/CreateArticle.js
  nginx/Dockerfile
  nginx/nginx.conf.template
  nginx/run_nginx.sh
Labels: enhancement, Priority: High

#22 Remove useless author parameter
  frontend/src/components/ArticleForm.js
Labels: bug, Priority: Low, Severity: Trivial

#28 Create LICENSE.MD
  LICENSE.MD
Labels: documentation, repo issue

#26 Fix bump version
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package.json
Labels: help wanted, Priority: Low, Severity: Trivial

#36 update tree in the readme
  README.md
Labels: bug, documentation, good first issue

#34 Add https
  .env.example
  .gitignore
  README.md
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf.template
Labels: enhancement, Security issue, Priority: High, Severity: Critical

#27 Introduce `bump.sh` script to automate version bumping
  README.md
  backend/package.json
  bump.sh
  frontend/package.json
  package.json
Labels: enhancement, Priority: Medium, Severity: Minor

#29 FEATURE: add an env-sharing script
  README.md
  scripts/gpg-share.sh
Labels: enhancement, Priority: Medium, Severity: Trivial

#45 Font size increased for login and sign up heading #43
  frontend/src/pages/Login.js
  frontend/src/pages/Signup.js
Labels: Priority: Medium, Severity: Trivial

#50 Updating license ISC to GPL3 in ./backend
  backend/package.json
Labels: good first issue, repo issue, Priority: Medium
