Repository iScsc/iscsc.fr, pull requests merged in 2022-12, with the labels that each got.

#48 FEATURE: add flag support to the `gpg-share` script
  scripts/gpg-share.sh
Labels: Priority: Low

#56 Move `bump.sh` script to `./scripts` and slight update
  bump.sh
  scripts/bump.sh
Labels: good first issue, repo issue, Priority: High

#51 Security updates
  frontend/package-lock.json
  frontend/package.json
  nginx/Dockerfile
Labels: Security issue, Priority: High, Severity: Major

#61 Fix backend header set twice
  backend/controllers/articleController.js
Labels: bug, Priority: Medium, Severity: Trivial

#66 0.1.1 version bump
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package.json
Labels: Priority: High
