Repository iScsc/iscsc.fr, pull requests merged in 2023-04, with the labels that each got.

#83 add a CI to format the code
  .github/workflows/prettier.yml
  README.md
  backend/app.js
  backend/controllers/articleController.js
  backend/controllers/userController.js
  backend/middleware/requireAuth.js
  backend/models/article.js
  backend/models/user.js
  backend/prettier.config.js
  backend/routes/articles.js
  backend/routes/users.js
  docker-compose.yml
  frontend/prettier.config.js
  frontend/public/index.html
  frontend/public/ressources/template.md
  frontend/src/App.js
  frontend/src/components/ArticleForm.js
  frontend/src/components/ArticleView.js
  frontend/src/components/Navbar.js
  frontend/src/context/ArticleContext.js
  frontend/src/context/AuthContext.js
  frontend/src/hooks/useArticlesContext.js
  frontend/src/hooks/useAuthContext.js
  frontend/src/hooks/useLogin.js
  frontend/src/hooks/useLogout.js
  frontend/src/hooks/useSignup.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/Login.js
  frontend/src/pages/Signup.js
  frontend/src/pages/blog/Article.js
  frontend/src/pages/blog/Blog.js
Labels: Priority: High

#91 FIX: remove the `with` block under `actions/checkout@v3` in `prettier`
  .github/workflows/prettier.yml
Labels: bug, repo issue, Priority: High

#88 Refactor backend docker environment towards a python flask backend
  .env.example
  .github/workflows/prettier.yml
  backend/Dockerfile
  backend/app.js
  backend/requirements.txt
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf.template
Labels: Priority: High, Severity: Critical, backend, refactoring

#81 Fix login redirection when browsing to /blog/create-article
  frontend/src/App.js
  frontend/src/pages/Login.js
  frontend/src/pages/Signup.js
Labels: bug, Priority: Medium

#92 Migrate database to localhost
  .env.example
  README.md
  backend/app.js
  docker-compose.yml
Labels: enhancement, Priority: High, backend
