Repository iScsc/iscsc.fr, pull requests merged in 2023-05, with the labels that each got.

#95 Fix database container
  .gitignore
  docker-compose.yml
Labels: bug, Priority: High, Severity: Critical, DB

#99 FEATURE: add `npm run` rule to prettify the code
  .github/pull_request_template.md
  package.json
Labels: Priority: High

#96 Created table of contents, corrected spelling and punctuation
  README.md
Labels: documentation, Priority: Low

#86 Create a containerize environment for development workflow
  .env.example
  .github/workflows/prettier.yml
  README.md
  backend/Dockerfile.dev
  docker-compose-dev.yml
  docker-compose.yml
  frontend/Dockerfile.dev
  frontend/package-lock.json
  frontend/package.json
  frontend/src/setupProxy.js
  nginx/Dockerfile
  nginx/nginx.conf.dev.template
  nginx/nginx.conf.prod.template
  nginx/run_nginx.sh
  scripts/setup-db-folder.sh
Labels: help wanted, Priority: High

#108 Add routes logic for users and articles
  backend/app.py
  backend/controllers/articleController.py
  backend/controllers/dummy_data.py
  backend/controllers/userController.py
  backend/routes/articles.py
  backend/routes/users.py
Labels: Priority: Medium, backend, backend refactoring
