Repository iScsc/iscsc.fr, pull requests merged in 2023-03, with the labels that each got.

#63 Fix empty context array when directly browsing to an URL
  frontend/src/context/ArticleContext.js
  frontend/src/pages/blog/Article.js
Labels: bug, Priority: Low, Severity: Minor

#71 Add subcommands to bump script
  scripts/bump.sh
Labels: Priority: Medium

#62 Add bash comments formatter
  scripts/bash-comments-formatter.py
Labels: enhancement, Priority: Low

#78 Add confirm dialog for article creation/deletion
  frontend/src/components/ArticlePreview.js
  frontend/src/pages/blog/CreateArticle.js
Labels: enhancement, Priority: Medium

#85 Fix website title and description
  frontend/public/index.html
Labels: bug, Priority: Low

#84 Update gitignore
  .gitignore
Labels: Priority: Low
